export const orderActionTypes = {
    SET_BOOKING_DATE: 'SET_BOOKING_DATE',
    SET_BOOKING_INFO: 'SET_BOOKING_INFO',
    INCREMENT_ADULTS: 'INCREMENT_ADULTS',
    DECREMENT_ADULTS: 'DECREMENT_ADULTS',
    INCREMENT_CHILDREN: 'INCREMENT_CHILDREN',
    DECREMENT_CHILDREN: 'DECREMENT_CHILDREN',
    BOOKING_ACCESS_DATE: 'BOOKING_ACCESS_DATE',
    BOOKING_EXIT_DATE: 'BOOKING_EXIT_DATE',
}
